export const PRISM_EXTENSIONS = {
    'python': 'Python',
    'go':'Go',
    'js': 'Javascript',
    'java': 'Java',
    // 'cpp': 'C++',
    'csharp': 'C#',
    'c': 'C',
    'swift':'Swift',
    'dart':'Dart',
    'rb': 'ruby',
    'scala': 'Scala',
    'kotlin': 'Kotlin',
    'css': 'CSS',
    'sql': 'SQL',
    'php':'PHP',
    'ps1': 'Powershell',
    'sh': 'Bash',
    'bat': 'Batch',
};
export const MONTHS=['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']